"""Single import point that loads all ORM models into Base.metadata."""
from app.models import (  # noqa: F401  (intentional side-effect import)
    AgentRun,
    Assignment,
    Base,
    ChatMessage,
    ChatSession,
    Course,
    CourseEnrollment,
    Grade,
    KnowledgeChunk,
    LecturerProfile,
    Lesson,
    Memory,
    MemoryEmbedding,
    Module,
    Notification,
    QuizQuestion,
    RefreshToken,
    StudentProfile,
    Submission,
    User,
    UserMemory,
)
